import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    listOfSongs: []
};

// Create a slice with a name and an initial state
export const songSlice = createSlice({
  name: "song", // name for the slice
  initialState, // initial state for the slice

  // Define reducers that can update the state
  reducers: {

    // Add reducers for more actions here
    setSongs: (state, action) => {
        state.listOfSongs = action.payload.setSongs;
    },

    updateSongData: (state, action) => {
        console.log(action.payload.id, "action.payload.id");
        console.log(action.payload.data, "action.payload.data");
        
        state.listOfSongs = state.listOfSongs.map((song) => {
            if (song._id === action.payload.id) {
                song = action.payload.data;
                console.warn("song", song);
                
            }
            return song;
        })
    }
  }
})


// Export the action creators generated by createSlice
export const { setSongs, updateSongData } = songSlice.actions;

// Export the reducer generated by createSlice
export default songSlice.reducer;


export const getSongsData = (state) => state.song.listOfSongs;
export const getSongsDataById = (state, id) => state.song.listOfSongs.find(song => song._id === id)
