import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    listOfSongs: []
};

// Create a slice with a name and an initial state
export const songSlice = createSlice({
  name: "song", // name for the slice
  initialState, // initial state for the slice

  // Define reducers that can update the state
  reducers: {

    // Add reducers for more actions here
    setSongs: (state, action) => {
        state.listOfSongs = action.payload.setSongs;
    },

  }
})


// Export the action creators generated by createSlice
export const { setSongs } = songSlice.actions;

// Export the reducer generated by createSlice
export default songSlice.reducer;


export const getSongsData = (state) => state.song.listOfSongs;
